### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by mtncgj123** [rpng/reach_ros_node#20]
When I run the code, It seems I have successfully connected to the RTK, but I can only receive the bytes data and got an error message like below  

**[INFO] [1656898801.067970]: Connecting to Reach RTK 192.168.42.1 on port 9001
[INFO] [1656898801.073358]: Successfully connected to device, starting publishing!
Traceback (most recent call last):
  File "/home/iasl/ZMJ_ws/src/reach_ros_node/scripts/nmea_tcp_driver", line 142, in <module>
    device.start()
  File "/home/iasl/ZMJ_ws/src/reach_ros_node/scripts/nmea_tcp_driver", line 62, in start
    data = self.buffered_readLine().strip()
  File "/home/iasl/ZMJ_ws/src/reach_ros_node/scripts/nmea_tcp_driver", line 125, in buffered_readLine
    line += part
TypeError: can only concatenate str (not "bytes") to str**

**Comment by dscroft** [comment]
You're running the node using python3. Try this fork instead. https://github.com/lights0123/reach_ros_node
